FROM node:20-alpine

WORKDIR /usr/src/app

# Copia só o package.json pra instalar as deps antes
COPY package*.json ./

# Instala todas as dependências (prod e dev)
RUN npm install

# Copia todo o código
COPY . .

# Exponha a porta padrão do Nest
EXPOSE 8001

# Rodar o Nest em modo de desenvolvimento com hot reload
CMD ["npm", "run", "start:dev"]
