services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--save", "60", "1000"]
    networks:
      - backend-network

  backend:
    container_name: plenna-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
      - "9229:9229"
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=railway
      - JWT_SECRET=samantinha
      - JWT_REFRESH_SECRET=samantinha
      - OPENAI_API_KEY=openai
      - PORT=8001
      - USE_FAKE_QUEUE=false
      - REDIS_URL=redis://redis:6379
      - EMAIL_HOST=email-smtp.sa-east-1.amazonaws.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=AKIA2JSBZUOU34GGTB45
      - EMAIL_PASS=BB9CQ/v/cyVKoP8N8YwJ0fl3x9xr/+G4qlLgU1PM24Tm
      - EMAIL_FROM="Plenna <no-reply@plenna.me>"
      - EMAIL_JOB_ATTEMPS=5
      - EMAIL_JOB_BACKOFF_MS=10000
      - EMAIL_WORKER_CONCURRENCY=5
    depends_on:
      - db
      - redis
    networks:
      - backend-network
    volumes:
      - ./:/app
      - backend_node_modules:/app/node_modules

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: railway
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
  backend_node_modules:
