services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=system
    command: npm run start:dev
    depends_on:
      - db
