services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "no", "--save", "60", "1000"]
    ports:
      - "6379:6379"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 20

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: railway
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - backend-network

  backend:
    container_name: plenna-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - PORT=8001
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=railway
      - JWT_SECRET=samantinha
      - JWT_REFRESH_SECRET=samantinha
      - OPENAI_API_KEY=openai
      - USE_FAKE_QUEUE=false
      - REDIS_URL=redis://redis:6379
      - FRONT_URL=http://localhost:3000/
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - backend-network
    ports:
      - "8001:8001"
      - "9229:9229"
    volumes:
      - ./:/app
      - backend_node_modules:/app/node_modules

  worker-appointments:
    container_name: w-appointments
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:worker:appointments:debug
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=railway
      - USE_FAKE_QUEUE=false
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - backend-network
    ports:
      - "9230:9229"
    volumes:
      - ./:/app
      - backend_node_modules:/app/node_modules

  worker-email:
    container_name: w-email
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:worker:email:debug
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - USE_FAKE_QUEUE=false
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_SECURE=false
      - EMAIL_USER=
      - EMAIL_PASS=
      - EMAIL_FROM=Plenna <no-reply@plenna.me>
      - EMAIL_JOB_ATTEMPS=5
      - EMAIL_JOB_BACKOFF_MS=10000
      - EMAIL_WORKER_CONCURRENCY=5
      - EMAIL_PROVIDER='smtp'
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend-network
    ports:
      - "9231:9229"
    volumes:
      - ./:/app
      - backend_node_modules:/app/node_modules

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - backend-network
      
networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
  backend_node_modules:
  
