export enum BankAccountTypeEnum {
    CHECKING = 'CHECKING', //CONTA CORRENTE
    SAVINGS = 'SAVINGS', //POUPANÇA
    DIGITAL_WALLET = 'DIGITAL_WALLET',
    INVESTMENT = 'INVESTMENT',
    PHYSICAL_WALLET = 'PHYSICAL_WALLET'
}