export enum FinancialEventsEnum {
    PAYMENT_POSTED = 'PAYMENT_POSTED',
    TRANSFER_POSTED = 'TRANSFER_POSTED',
    REVERSAL = 'REVERSAL',
    OPENING_BALANCE = 'OPENING_BALANCE',
    REVENUE_RECEIVED = 'REVENUE_RECEIVED',
    CHARGE_GENERATED = 'CHARGE_GENERATED',
    CHARGE_PAID = 'CHARGE_PAID',
    CHARGE_CANCELED = 'CHARGE_CANCELED',
    CHARGE_EXPIRED = 'CHARGE_EXPIRED',
    CHARGE_REFUNDED = 'CHARGE_REFUNDED',
    REVENUE_RECOGNIZED = 'REVENUE_RECOGNIZED',
    EXPENSE_RECOGNIZED = 'EXPENSE_RECOGNIZED',
}