export enum FinancialEventsEnum {
    EXPENSE_POSTED = 'EXPENSE_POSTED',
    REVENUE_POSTED = 'REVENUE_POSTED',
    TRANSFER_POSTED = 'TRANSFER_POSTED',
    ADJUSTMENT = 'ADJUSTMENT',
    REVERSAL = 'REVERSAL',
    OPENING_BALANCE = 'OPENING_BALANCE'
}