export enum FinancialEventsEnum {
    PAYMENT_POSTED = 'PAYMENT_POSTED',
    TRANSFER_POSTED = 'TRANSFER_POSTED',
    REVERSAL = 'REVERSAL',
    OPENING_BALANCE = 'OPENING_BALANCE',
    REVENUE_RECEIVED = 'REVENUE_RECEIVED'
}