export enum LedgerEntryTypeEnum {
    R = 'REVENUE',
    E = 'EXPENSE',
    T = 'TRANSFER',
    C = 'CHECKING',
    S = 'SAVINGS',
    INVOICE = 'INVOICE',
    P_WALLET = 'PHYSICAL_WALLET',
    D_WALLET = 'DIGITAL_WALLET',
    INVESTMENT = 'INVESTMENT',
    ACCOUNT_OPENING = 'ACCOUNT_OPENING',
    CHARGE = 'CHARGE'
}