ALTER TABLE refresh_token
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS user_agent VARCHAR(512) NULL,
    ADD COLUMN IF NOT EXISTS created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS last_used_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
