CREATE TABLE IF NOT EXISTS appointment_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    clientId INT NOT NULL,
    appointmentType VARCHAR(100) NOT NULL,
    isActive TINYINT(1) NOT NULL DEFAULT 0,
    recurrence VARCHAR(32) NULL,
    timezone VARCHAR(64) NULL,
    config JSON NULL,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY idx_client_type (clientId, appointmentType)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
